const KEY='grouporder-v5';
const $=s=>document.querySelector(s), money=n=>`$${Number(n||0).toFixed(2)}`, uid=()=>Math.random().toString(36).slice(2,10);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seedShops=[{id:'bakery',name:'Golden Bakery',menus:[{id:'bakery-menu',name:'Regular Menu',items:[['Egg Tart',15,10,'piece'],['Pineapple Bun',12,8,'piece'],['Wife Cake',18,6,'piece'],['Milk Tea',20,10,'bottle']]}]},{id:'fruit',name:'Fresh Fruit Market',menus:[{id:'fruit-menu',name:'Regular Menu',items:[['Mango',24,6,'piece'],['Strawberry Box',18,4,'box'],['Blueberry Box',20,5,'box'],['Grape Pack',16,8,'pack']]}]}].map(s=>({...s,menus:s.menus.map(m=>({...m,items:m.items.map(([name,price,volume,unit])=>({id:uid(),name,price,volume,unit}))}))}));
let db={shops:seedShops,people:[{id:'p1',name:'Amery'},{id:'p2',name:'Judy'},{id:'p3',name:'Joyce'},{id:'p4',name:'Anthony'}],sessions:[],current:null};
function migrate(){try{const old=JSON.parse(localStorage.getItem(KEY));if(old)db=old;else{const old2=JSON.parse(localStorage.getItem('grouporder-v3'));if(old2?.shops){db.shops=old2.shops.map(s=>({...s,menus:[{id:uid(),name:'Imported Menu',items:(s.items||[]).map(i=>({...i}))}]}));db.people=old2.people||db.people;db.sessions=[]}}}catch{};if(!db.shops?.length)db.shops=seedShops;if(!db.people)db.people=[];if(!db.sessions)db.sessions=[];if(!db.shops[0].menus?.length)db.shops.forEach(s=>s.menus=[{id:uid(),name:'Menu',items:[]}]);if(!db.current&&db.sessions[0])db.current=db.sessions[0].id}
function save(){localStorage.setItem(KEY,JSON.stringify(db));if($('#saveStatus'))$('#saveStatus').textContent='Saved'}
const session=()=>db.sessions.find(x=>x.id===db.current), currentShop=()=>db.shops.find(x=>x.id===session()?.shopId), currentMenu=()=>currentShop()?.menus.find(m=>m.id===session()?.menuId), activeMenu=()=>db.shops.find(s=>s.id===$('#menuShopSelect')?.value)?.menus.find(m=>m.id===$('#menuSelect')?.value);
function newSession(){const date=prompt('Session date (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;let list=db.shops.map((s,i)=>`${i+1}. ${s.name}`).join('\n');const a=prompt(`Choose shop by number, or type a new shop name:\n\n${list}`,'1');if(!a)return;let shop=db.shops[Number(a)-1];if(!shop){shop={id:uid(),name:a,menus:[{id:uid(),name:'Menu',items:[]} ]};db.shops.push(shop)}const menus=shop.menus.map((m,i)=>`${i+1}. ${m.name}`).join('\n');const ma=prompt(`Choose menu for ${shop.name}:\n\n${menus}`,'1');if(!ma)return;let menu=shop.menus[Number(ma)-1];if(!menu){menu={id:uid(),name:ma,items:[]};shop.menus.push(menu)}const s={id:uid(),date,shopId:shop.id,menuId:menu.id,items:menu.items.map(it=>({id:uid(),catalogId:it.id,name:it.name,price:+it.price,volume:+it.volume,unit:it.unit||'piece',participants:{}})),finalized:false};db.people.forEach(p=>s.items.forEach(it=>it.participants[p.id]={checked:false,qty:0}));db.sessions.unshift(s);db.current=s.id;save();render();activate('order')}
function render(){renderSessions();renderMenuSelector();renderMenu();renderPeople();renderOrder();renderSummary();renderHistory()}
function renderSessions(){const e=$('#sessionSelect');if(!e)return;e.innerHTML=db.sessions.map(s=>{const sh=db.shops.find(x=>x.id===s.shopId),m=sh?.menus.find(x=>x.id===s.menuId);return `<option value="${s.id}">${s.date.replaceAll('-','')} · ${esc(sh?.name||'')} · ${esc(m?.name||'')}${s.finalized?' ✓':''}</option>`}).join('')||'<option>No sessions</option>';if(db.current)e.value=db.current;const s=session(),sh=currentShop(),m=currentMenu();if(s){$('#sessionDate').value=s.date;$('#sessionShop').textContent=sh?`Shop: ${sh.name}`:'';$('#sessionMenu').textContent=m?`Menu: ${m.name}`:''}}
function renderMenuSelector(){const e=$('#menuShopSelect');if(!e)return;e.innerHTML=db.shops.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');if(!e.value&&db.shops[0])e.value=db.shops[0].id;const sh=db.shops.find(s=>s.id===e.value)||db.shops[0];if(sh){e.value=sh.id;let ms=$('#menuSelect');if(!ms){ms=document.createElement('select');ms.id='menuSelect';ms.className='select';$('#menuName').replaceWith(ms)}ms.innerHTML=sh.menus.map(m=>`<option value="${m.id}">${esc(m.name)}</option>`).join('');if(!ms.value&&sh.menus[0])ms.value=sh.menus[0].id;$('#menuName')?.remove()}}
function selectedMenu(){const sh=db.shops.find(s=>s.id===$('#menuShopSelect')?.value)||db.shops[0];const ms=$('#menuSelect');return {sh,m:sh?.menus.find(m=>m.id===ms?.value)||sh?.menus[0]}}
function renderMenu(){const box=$('#menuTable'),empty=$('#emptyMenu'),{m}=selectedMenu();if(!box)return;if(!m){box.innerHTML='';empty.style.display='block';return}box.innerHTML=`<table><thead><tr><th>Item</th><th>Price</th><th>Pieces / volume</th><th>Unit</th><th></th></tr></thead><tbody>${m.items.map((it,i)=>`<tr><td><input class="menu-edit" data-i="${i}" data-k="name" value="${esc(it.name)}"></td><td><input class="menu-edit" data-i="${i}" data-k="price" type="number" step="0.01" value="${it.price}"></td><td><input class="menu-edit" data-i="${i}" data-k="volume" type="number" min="1" step="1" value="${it.volume}"></td><td><input class="menu-edit" data-i="${i}" data-k="unit" value="${esc(it.unit||'piece')}"></td><td><button class="icon-btn menu-del" data-i="${i}">×</button></td></tr>`).join('')}</tbody></table>`;empty.style.display=m.items.length?'none':'block';box.querySelectorAll('.menu-edit').forEach(x=>x.onchange=e=>{const {m}=selectedMenu(),i=+e.target.dataset.i,k=e.target.dataset.k;m.items[i][k]=k==='price'||k==='volume'?+e.target.value:e.target.value;save();renderMenu()});box.querySelectorAll('.menu-del').forEach(x=>x.onclick=()=>{const {m}=selectedMenu();m.items.splice(+x.dataset.i,1);save();renderMenu()})}
function addShop(){const name=prompt('New shop name?');if(!name)return;const shop={id:uid(),name,menus:[{id:uid(),name:'Menu',items:[]}]};db.shops.push(shop);save();render();$('#menuShopSelect').value=shop.id;renderMenuSelector();renderMenu()}
function addMenuItem(){const {m}=selectedMenu();if(!m)return; m.items.push({id:uid(),name:'New item',price:0,volume:1,unit:'piece'});save();renderMenu()}
function importCSV(file){const {m}=selectedMenu();if(!m)return;const r=new FileReader();r.onload=()=>{String(r.result).split(/\r?\n/).filter(Boolean).forEach(line=>{const [name,price,volume,unit]=line.split(',');if(name)m.items.push({id:uid(),name:name.trim(),price:+price||0,volume:+volume||1,unit:(unit||'piece').trim()})});save();renderMenu()};r.readAsText(file)}
function exportCSV(){const {sh,m}=selectedMenu();if(!m)return;const csv='Item,Price,Pieces,Unit\n'+m.items.map(i=>`${i.name},${i.price},${i.volume},${i.unit}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`${sh.name}-${m.name}.csv`;a.click()}
function addPerson(){const name=prompt('Participant name?');if(!name)return;db.people.push({id:uid(),name});db.sessions.forEach(s=>s.items.forEach(i=>i.participants[db.people.at(-1).id]={checked:false,qty:0}));save();render()}
function renderPeople(){const b=$('#peopleFull');if(!b)return;b.innerHTML=db.people.map((p,i)=>`<div class="person-row"><input class="person-name" data-i="${i}" value="${esc(p.name)}"><button class="icon-btn del-person" data-i="${i}">×</button></div>`).join('');b.querySelectorAll('.person-name').forEach(x=>x.onchange=e=>{db.people[+e.target.dataset.i].name=e.target.value;save();render()});b.querySelectorAll('.del-person').forEach(x=>x.onclick=()=>{db.people.splice(+x.dataset.i,1);save();render()})}
function allocate(it){const ps=db.people.filter(p=>it.participants[p.id]?.checked),base=ps.length?Math.floor(it.volume/ps.length):0,rem=ps.length?it.volume-base*ps.length:0;ps.forEach((p,i)=>it.participants[p.id].qty=base+(i<rem?1:0))}
const allocated=it=>db.people.reduce((n,p)=>n+(+it.participants[p.id]?.qty||0),0);
function renderOrder(){const b=$('#orderItems'),s=session();if(!b)return;b.innerHTML=(s?.items||[]).map((it,ii)=>{const left=it.volume-allocated(it);return `<div class="order-item ${left?'warning':''}"><div class="order-head"><div><strong>${esc(it.name)}</strong><div class="muted">${money(it.price)} · ${it.volume} ${esc(it.unit)}</div></div></div><div class="participant-picks">${db.people.map(p=>{const a=it.participants[p.id]||{checked:false,qty:0};return `<label class="pick-person"><input type="checkbox" data-item="${ii}" data-pid="${p.id}" ${a.checked?'checked':''} ${s.finalized?'disabled':''}> ${esc(p.name)} <input class="qty" type="number" min="0" max="${it.volume}" value="${a.qty}" data-i="${ii}" data-p="${p.id}" ${!a.checked||s.finalized?'disabled':''}></label>`}).join('')}</div><div class="allocation-status">${left?'⚠ '+left+' '+it.unit+(left===1?'':'s')+' unallocated':'✓ Fully allocated'}</div></div>`}).join('');if($('#emptyOrder'))$('#emptyOrder').style.display=s?.items?.length?'none':'block';b.querySelectorAll('input[type=checkbox]').forEach(x=>x.onchange=e=>{const it=s.items[+e.target.dataset.item],a=it.participants[e.target.dataset.pid];a.checked=e.target.checked;if(a.checked)allocate(it);else a.qty=0;save();renderOrder();renderSummary()});b.querySelectorAll('.qty').forEach(x=>x.onchange=e=>{const it=s.items[+e.target.dataset.i];it.participants[e.target.dataset.p].qty=Math.max(0,Math.min(it.volume,+e.target.value||0));save();renderOrder();renderSummary()})}
function renderSummary(){const b=$('#summary'),s=session();if(!b||!s)return;const complete=s.items.length&&s.items.every(i=>allocated(i)===i.volume);b.innerHTML=`<div class="session-state ${complete?'ok':'warning'}">${s.finalized?'✓ Order finalised':complete?'✓ All pieces allocated':'⚠ Allocate every piece before finalising'}</div>`+db.people.map(p=>{let total=0,lines=[];s.items.forEach(i=>{const q=i.participants[p.id]?.qty||0;if(q){const a=i.price*q/i.volume;total+=a;lines.push(`${i.name} × ${q} = ${money(a)}`)}});return `<div class="summary-person"><div class="summary-top"><strong>${esc(p.name)}</strong><strong>${money(total)}</strong></div>${lines.map(l=>`<div class="detail">${esc(l)}</div>`).join('')||'<div class="detail">No items</div>'}</div>`}).join('')}
function renderHistory(){const b=$('#historyList');if(!b)return;b.innerHTML=db.sessions.map(s=>{const sh=db.shops.find(x=>x.id===s.shopId),m=sh?.menus.find(x=>x.id===s.menuId);return `<div class="history-row"><div><strong>${s.date.replaceAll('-','')} · ${esc(sh?.name||'')} · ${esc(m?.name||'')}</strong><span>${s.items.length} items · ${s.finalized?'Finalised':'Draft'}</span></div><button class="secondary-btn hist" data-id="${s.id}">Open</button></div>`}).join('')||'<div class="empty">No sessions yet.</div>';b.querySelectorAll('.hist').forEach(x=>x.onclick=()=>{db.current=x.dataset.id;save();render();activate('order')})}
async function copy(t){try{await navigator.clipboard.writeText(t);alert('Copied!')}catch{prompt('Copy:',t)}}
function copyOrder(){const s=session();copy((s?.items||[]).map(i=>`${i.name} | ${i.volume} ${i.unit} | ${money(i.price)}`).join('\n'))}
function copyAll(){const s=session();copy(db.people.map(p=>{let t=0,l=[];(s?.items||[]).forEach(i=>{const q=i.participants[p.id]?.qty||0;if(q){const a=i.price*q/i.volume;t+=a;l.push(`${i.name} × ${q} = ${money(a)}`)}});return `${p.name}\n${l.join('\n')}\nTotal: ${money(t)}`}).join('\n\n'))}
function activate(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`tab-${tab}`))}
$('#newSessionBtn').onclick=newSession;$('#sessionSelect').onchange=e=>{db.current=e.target.value;save();render()};$('#sessionDate').onchange=e=>{if(session()){session().date=e.target.value;save();renderSessions()}};$('#deleteSessionBtn').onclick=()=>{if(confirm('Delete this session?')){db.sessions=db.sessions.filter(x=>x.id!==db.current);db.current=db.sessions[0]?.id||null;save();render()}};$('#addShopBtn').onclick=addShop;$('#addMenuItemBtn').onclick=addMenuItem;$('#importBtn').onclick=()=>$('#csvInput').click();$('#csvInput').onchange=e=>e.target.files[0]&&importCSV(e.target.files[0]);$('#exportBtn').onclick=exportCSV;$('#menuShopSelect').onchange=()=>{renderMenuSelector();renderMenu()};$('#addPersonBtn').onclick=addPerson;$('#copyOrderBtn').onclick=copyOrder;$('#copyAllBtn').onclick=copyAll;$('#resetBtn').onclick=()=>{if(confirm('Reset saved data to the two demo shops?')){localStorage.removeItem(KEY);location.reload()}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>activate(b.dataset.tab));
migrate();render();