const KEY='grouporder-v3';
const $=s=>document.querySelector(s), money=n=>`$${Number(n||0).toFixed(2)}`;
const uid=()=>Math.random().toString(36).slice(2,10), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const demoShops=[{id:'bakery',name:'Golden Bakery',items:[['Egg Tart',15,10,'piece'],['Pineapple Bun',12,8,'piece'],['Wife Cake',18,6,'piece'],['Milk Tea',20,10,'bottle']]},{id:'fruit',name:'Fresh Fruit Market',items:[['Mango',24,6,'piece'],['Strawberry Box',18,4,'box'],['Blueberry Box',20,5,'box'],['Grape Pack',16,8,'pack']]}].map(s=>({...s,items:s.items.map(([name,price,volume,unit])=>({id:uid(),name,price,volume,unit}))}));
let db={shops:demoShops,people:[{id:'p1',name:'Amery'},{id:'p2',name:'Judy'},{id:'p3',name:'Joyce'},{id:'p4',name:'Anthony'}],sessions:[],current:null};
function save(){localStorage.setItem(KEY,JSON.stringify(db));if($('#saveStatus'))$('#saveStatus').textContent='Saved'}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x)db=x}catch{};if(!db.shops?.length)db.shops=demoShops;if(!db.people)db.people=[];if(!db.sessions)db.sessions=[];if(!db.current&&db.sessions[0])db.current=db.sessions[0].id;render()}
const session=()=>db.sessions.find(x=>x.id===db.current);
function newSession(){const date=prompt('Session date (YYYY-MM-DD):',new Date().toISOString().slice(0,10));if(!date)return;const list=db.shops.map((s,i)=>`${i+1}. ${s.name}`).join('\n');const a=prompt(`Choose shop by number, or type a new shop name:\n\n${list}`,'1');if(!a)return;let shop=db.shops[Number(a)-1];if(!shop){shop={id:uid(),name:a,items:[]};db.shops.push(shop)}db.sessions.unshift({id:uid(),date,shopId:shop.id,items:[],finalized:false});db.current=db.sessions[0].id;save();render();activate('order')}
function render(){renderSessions();renderCatalogue();renderPeople();renderOrder();renderSummary();renderHistory()}
function renderSessions(){const e=$('#sessionSelect');if(!e)return;e.innerHTML=db.sessions.map(s=>{const sh=db.shops.find(x=>x.id===s.shopId);return `<option value="${s.id}">${s.date.replaceAll('-','')} · ${esc(sh?.name||'Unknown')}${s.finalized?' ✓':''}</option>`}).join('')||'<option>No sessions</option>';if(db.current)e.value=db.current;const s=session();if(s){if($('#sessionDate'))$('#sessionDate').value=s.date;if($('#sessionShop'))$('#sessionShop').value=db.shops.find(x=>x.id===s.shopId)?.name||''}}
function renderCatalogue(){const s=session(),shop=db.shops.find(x=>x.id===s?.shopId),box=$('#catalogue');if(!box)return;box.innerHTML=(shop?.items||[]).map((it,i)=>`<div class="catalog-item"><div><strong>${esc(it.name)}</strong><span>${money(it.price)} · ${it.volume} ${esc(it.unit)}</span></div><button class="primary-btn pick" data-i="${i}">${s?.items.some(x=>x.catalogId===it.id)?'Added':'Pick'}</button></div>`).join('');if($('#emptyCatalogue'))$('#emptyCatalogue').style.display=shop?.items?.length?'none':'block';box.querySelectorAll('.pick').forEach(b=>b.onclick=()=>pickItem(shop.items[+b.dataset.i]))}
function pickItem(it){const s=session();if(!s||s.finalized||s.items.some(x=>x.catalogId===it.id))return;s.items.push({id:uid(),catalogId:it.id,name:it.name,price:+it.price,volume:+it.volume,unit:it.unit,participants:{}});db.people.forEach(p=>s.items.at(-1).participants[p.id]={checked:false,qty:0});save();render();activate('order')}
function addPerson(){const name=prompt('Participant name?');if(!name)return;db.people.push({id:uid(),name});save();render()}
function renderPeople(){['#peopleQuick','#peopleFull'].forEach(sel=>{const b=$(sel);if(!b)return;b.innerHTML=db.people.map((p,i)=>`<div class="person-row"><input class="person-name" data-i="${i}" value="${esc(p.name)}"><button class="icon-btn del-person" data-i="${i}">×</button></div>`).join('');b.querySelectorAll('.person-name').forEach(e=>e.onchange=v=>{db.people[+v.target.dataset.i].name=v.target.value;save();render()});b.querySelectorAll('.del-person').forEach(e=>e.onclick=()=>{const id=db.people[+e.dataset.i].id;db.people.splice(+e.dataset.i,1);db.sessions.forEach(s=>s.items.forEach(i=>delete i.participants[id]));save();render()})})}
function allocate(it){const ps=db.people.filter(p=>it.participants[p.id]?.checked),base=ps.length?Math.floor(it.volume/ps.length):0,rem=ps.length?it.volume-base*ps.length:0;ps.forEach((p,i)=>it.participants[p.id].qty=base+(i<rem?1:0))}
const allocated=it=>db.people.reduce((n,p)=>n+(+it.participants[p.id]?.qty||0),0);
function renderOrder(){const box=$('#orderItems'),s=session();if(!box)return;if(!s){box.innerHTML='';return}box.innerHTML=s.items.map((it,ii)=>{const left=it.volume-allocated(it);return `<div class="order-item ${left?'warning':''}"><div class="order-head"><div><strong>${esc(it.name)}</strong><div class="muted">${money(it.price)} · ${it.volume} ${esc(it.unit)}</div></div><button class="icon-btn del-order" data-i="${ii}" ${s.finalized?'disabled':''}>×</button></div><div class="participant-picks">${db.people.map(p=>{const a=it.participants[p.id]||{checked:false,qty:0};return `<label class="pick-person"><input type="checkbox" data-item="${ii}" data-pid="${p.id}" ${a.checked?'checked':''} ${s.finalized?'disabled':''}> ${esc(p.name)} <input class="qty" type="number" min="0" max="${it.volume}" step="1" data-qitem="${ii}" data-qpid="${p.id}" value="${a.qty}" ${!a.checked||s.finalized?'disabled':''}></label>`}).join('')}</div><div class="allocation-status">${left?'⚠ '+left+' '+it.unit+(left===1?'':'s')+' unallocated':'✓ Fully allocated'}</div></div>`}).join('');if($('#emptyOrder'))$('#emptyOrder').style.display=s.items.length?'none':'block';box.querySelectorAll('input[type=checkbox]').forEach(e=>e.onchange=v=>{const it=s.items[+v.target.dataset.item],a=it.participants[v.target.dataset.pid]||{checked:false,qty:0};a.checked=v.target.checked;a.qty=0;it.participants[v.target.dataset.pid]=a;if(a.checked)allocate(it);save();renderOrder();renderSummary()});box.querySelectorAll('.qty').forEach(e=>e.onchange=v=>{const it=s.items[+v.target.dataset.qitem];it.participants[v.target.dataset.qpid].qty=Math.max(0,Math.min(it.volume,+v.target.value||0));save();renderOrder();renderSummary()})}
function renderSummary(){const b=$('#summary'),s=session();if(!b)return;if(!s){b.innerHTML='';return}const complete=s.items.length&&s.items.every(i=>allocated(i)===i.volume);b.innerHTML=`<div class="session-state ${complete?'ok':'warning'}">${s.finalized?'✓ Order finalised':complete?'✓ All pieces allocated':'⚠ Allocate every piece before finalising'}</div>`+db.people.map(p=>{let total=0,lines=[];s.items.forEach(i=>{const q=i.participants[p.id]?.qty||0;if(q){const a=i.price*q/i.volume;total+=a;lines.push(`${i.name} × ${q} = ${money(a)}`)}});return `<div class="summary-person"><div class="summary-top"><strong>${esc(p.name)}</strong><strong>${money(total)}</strong></div>${lines.map(l=>`<div class="detail">${esc(l)}</div>`).join('')||'<div class="detail">No items</div>'}<button class="secondary-btn copy-person" data-pid="${p.id}">Copy order</button></div>`}).join('');b.querySelectorAll('.copy-person').forEach(x=>x.onclick=()=>copyParticipant(x.dataset.pid))}
function renderHistory(){const b=$('#historyList');if(!b)return;b.innerHTML=db.sessions.map(s=>{const sh=db.shops.find(x=>x.id===s.shopId);return `<div class="history-row"><div><strong>${s.date.replaceAll('-','')} · ${esc(sh?.name||'')}</strong><span>${s.items.length} items · ${s.finalized?'Finalised':'Draft'}</span></div><button class="secondary-btn hist" data-id="${s.id}">Open</button></div>`}).join('')||'<div class="empty">No sessions yet.</div>';b.querySelectorAll('.hist').forEach(x=>x.onclick=()=>{db.current=x.dataset.id;save();render();activate('order')})}
async function copy(t){try{await navigator.clipboard.writeText(t);alert('Copied!')}catch{prompt('Copy:',t)}}
function copyParticipant(pid){const s=session(),p=db.people.find(x=>x.id===pid),sh=db.shops.find(x=>x.id===s.shopId);let total=0,l=[];s.items.forEach(i=>{const q=i.participants[p.id]?.qty||0;if(q){const a=i.price*q/i.volume;total+=a;l.push(`${i.name} × ${q} = ${money(a)}`)}});copy(`${sh?.name} · ${s.date.replaceAll('-','')}\n${p.name}\n${l.join('\n')}\nTotal: ${money(total)}`)}
function copyAll(){const s=session();copy(db.people.map(p=>{let t=0,l=[];s.items.forEach(i=>{const q=i.participants[p.id]?.qty||0;if(q){const a=i.price*q/i.volume;t+=a;l.push(`${i.name} × ${q} = ${money(a)}`)}});return `${p.name}\n${l.join('\n')}\nTotal: ${money(t)}`}).join('\n\n'))}
function copyOrder(){const s=session(),sh=db.shops.find(x=>x.id===s.shopId);copy(`${sh?.name} · ${s.date.replaceAll('-','')}\n`+s.items.map(i=>`${i.name} | ${i.volume} ${i.unit} | ${money(i.price)}`).join('\n'))}
function addShopItem(){const s=session(),sh=db.shops.find(x=>x.id===s?.shopId);if(!sh)return alert('Create a session first.');const name=prompt('Item name?');if(!name)return;const price=prompt('Price?','0'),volume=prompt('Pieces?','1');sh.items.push({id:uid(),name,price:+price||0,volume:+volume||1,unit:'piece'});save();renderCatalogue()}
function importCSV(file){const sh=db.shops.find(x=>x.id===session()?.shopId);if(!sh)return;const r=new FileReader();r.onload=()=>{String(r.result).split(/\r?\n/).filter(Boolean).forEach(line=>{const[n,p,v,u]=line.split(',');if(n)sh.items.push({id:uid(),name:n.trim(),price:+p||0,volume:+v||1,unit:(u||'piece').trim()})});save();renderCatalogue()};r.readAsText(file)}
function activate(tab){document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.toggle('hidden',x.id!==`tab-${tab}`));if(tab==='history')renderHistory()}
if($('#newSessionBtn'))$('#newSessionBtn').onclick=newSession;if($('#sessionSelect'))$('#sessionSelect').onchange=e=>{db.current=e.target.value;save();render()};if($('#addShopItemBtn'))$('#addShopItemBtn').onclick=addShopItem;if($('#importBtn'))$('#importBtn').onclick=()=>$('#csvInput').click();if($('#csvInput'))$('#csvInput').onchange=e=>e.target.files[0]&&importCSV(e.target.files[0]);if($('#addPersonBtn'))$('#addPersonBtn').onclick=addPerson;if($('#addPersonBtn2'))$('#addPersonBtn2').onclick=addPerson;if($('#copyOrderBtn'))$('#copyOrderBtn').onclick=copyOrder;if($('#copyAllBtn'))$('#copyAllBtn').onclick=copyAll;if($('#deleteSessionBtn'))$('#deleteSessionBtn').onclick=()=>{if(confirm('Delete this session?')){db.sessions=db.sessions.filter(x=>x.id!==db.current);db.current=db.sessions[0]?.id||null;save();render()}};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>activate(b.dataset.tab));
if(!document.querySelector('[data-tab="history"]')){const b=document.createElement('button');b.className='tab';b.dataset.tab='history';b.textContent='History';document.querySelector('.tabs').appendChild(b);b.onclick=()=>activate('history');const sec=document.createElement('section');sec.id='tab-history';sec.className='tab-panel hidden';sec.innerHTML='<section class="card"><div class="card-head"><div><h2>Historical sessions</h2><p class="muted">Open previous group buys and review stored allocations.</p></div></div><div id="historyList"></div></section>';document.querySelector('main.container').insertBefore(sec,document.querySelector('footer'))}
if(!document.querySelector('#finalizeBtn')){const f=document.createElement('button');f.id='finalizeBtn';f.className='primary-btn';f.textContent='Finalise Order';const h=document.querySelector('#tab-order .card-head');if(h)h.appendChild(f);f.onclick=()=>{const s=session();if(!s.items.length||s.items.some(i=>allocated(i)!==i.volume)){alert('Cannot finalise: every piece must be allocated.');return}s.finalized=true;save();render();activate('settlement')}}
load();