const state={items:[],people:[],allocations:{},mode:'quantity'};
const $=s=>document.querySelector(s); const money=n=>`$${Number(n||0).toFixed(2)}`;
function save(){localStorage.setItem('grouporder',JSON.stringify(state));$('#saveStatus').textContent='Saved';}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('grouporder'))||{})}catch{};render();}
function render(){
 $('#items').innerHTML=''; $('#people').innerHTML='';
 state.items.forEach((x,i)=>{const t=$('#itemTemplate').content.cloneNode(true);const r=t.querySelector('.item-row');t.querySelector('.item-name').value=x.name||'';t.querySelector('.item-price').value=x.price??'';t.querySelector('.item-qty').value=x.qty??1;t.querySelector('.item-name').oninput=e=>{x.name=e.target.value;save();renderAllocation()};t.querySelector('.item-price').oninput=e=>{x.price=+e.target.value||0;save();render()};t.querySelector('.item-qty').oninput=e=>{x.qty=Math.max(1,+e.target.value||1);save();render()};t.querySelector('.delete-item').onclick=()=>{state.items.splice(i,1);save();render()};$('#items').appendChild(t)});
 state.people.forEach((x,i)=>{const t=$('#personTemplate').content.cloneNode(true);t.querySelector('.person-name').value=x.name||'';t.querySelector('.person-name').oninput=e=>{x.name=e.target.value;save();renderAllocation()};t.querySelector('.delete-person').onclick=()=>{state.people.splice(i,1);save();render()};$('#people').appendChild(t)});
 $('#emptyItems').style.display=state.items.length?'none':'block';$('#emptyPeople').style.display=state.people.length?'none':'block';$('#allocationMode').value=state.mode;renderAllocation();
}
function renderAllocation(){const a=$('#allocation'), empty=$('#emptyAllocation'); if(!state.items.length||!state.people.length){a.innerHTML='';empty.style.display='block';renderSummary();return} empty.style.display='none';let html='<table><thead><tr><th>Item</th><th>Price</th>';state.people.forEach(p=>html+=`<th>${esc(p.name||'Unnamed')}</th>`);html+='<th>Allocated</th></tr></thead><tbody>';
 state.items.forEach((item,ii)=>{html+=`<tr><td><strong>${esc(item.name||'Unnamed')}</strong><br><small>${item.qty} unit${item.qty==1?'':'s'}</small></td><td>${money(item.price)}</td>`;state.people.forEach((p,pi)=>{const key=`${ii}-${pi}`;const val=state.allocations[key]??0;html+=`<td><input type="number" min="0" step="0.25" value="${val}" data-key="${key}"></td>`});let total=state.people.reduce((s,p,pi)=>s+(+state.allocations[`${ii}-${pi}`]||0),0);html+=`<td>${total} / ${item.qty}</td></tr>`});html+='</tbody></table>';a.innerHTML=html;a.querySelectorAll('input').forEach(inp=>inp.oninput=e=>{let v=Math.max(0,+e.target.value||0);if(state.mode==='quantity')v=Math.min(v,state.items[+e.target.dataset.key.split('-')[0]].qty);state.allocations[e.target.dataset.key]=v;save();renderAllocation();});renderSummary();}
function renderSummary(){const s=$('#summary');if(!state.people.length){s.innerHTML='<div class="empty">No participants yet.</div>';return}const totals=state.people.map((p,pi)=>{let amount=0,units=0;state.items.forEach((item,ii)=>{const q=+state.allocations[`${ii}-${pi}`]||0;units+=q;amount+=item.qty?(item.price*q/item.qty):0});return {p,amount,units}});const rawTotal=state.items.reduce((x,i)=>x+i.price,0);s.innerHTML=totals.map(x=>`<div class="summary-person"><div class="name">${esc(x.p.name||'Unnamed')}</div><div class="amount">${money(x.amount)}</div><div class="detail">${x.units} allocated unit${x.units==1?'':'s'}</div></div>`).join('');$('#orderTotal').textContent=money(rawTotal);}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('#addItemBtn').onclick=()=>{state.items.push({name:'',price:0,qty:1});save();render()};$('#addPersonBtn').onclick=()=>{state.people.push({name:''});save();render()};$('#allocationMode').onchange=e=>{state.mode=e.target.value;save();renderAllocation()};$('#resetBtn').onclick=()=>{if(confirm('Reset this order?')){state.items=[];state.people=[];state.allocations={};save();render()}};
$('#copyBtn').onclick=async()=>{const text=state.people.map((p,pi)=>{let amount=0;state.items.forEach((i,ii)=>amount+=(i.price*(+state.allocations[`${ii}-${pi}`]||0)/i.qty));return `${p.name||'Unnamed'}: ${money(amount)}`}).join('\n');await navigator.clipboard.writeText(`GroupOrder settlement\n${text}`);$('#copyBtn').textContent='Copied!';setTimeout(()=>$('#copyBtn').textContent='Copy summary',1200)};
load();
